In [2]:
import numpy as np
print(np.__version__)


2.5.1


In [3]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr = np.array([[1, 2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
arr = np.array([[[1, 2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [12]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.arange(0,10,2)
# np.arange(0,5,5)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
a=np.array([1,2,3,4,5])
print(a)
print(a.dtype)

[1 2 3 4 5]
int64


In [24]:
a=np.array([1,2,3,4,5],dtype=np.float32)
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float32


In [28]:
c=a.astype(np.float64)
print(c)

[1. 2. 3. 4. 5.]


In [29]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [31]:
a=np.arange(12)
print(a)
b=a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
c=a.reshape(2,-1)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [33]:
arr1=np.array([[1,2],[3,4]])
print(arr1)
print(arr1.flatten())
print(arr1.ravel())

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
print(np.concatenate([a,b]))


[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [37]:
a=np.arange(9)
print(a)
np.split(a,9)

[0 1 2 3 4 5 6 7 8]


[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8])]

In [38]:
a=np.array([1,2,3])
np.append(a,[4,5])
np.insert(a,1,99)
np.delete(a,0)

array([2, 3])

In [39]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [40]:
b=print(np.append(a,[4,5]))
print(a)
print(b)

b=(np.append(a,[4,5]))
print(a)
print(b)

[1 2 3 4 5]
[1 2 3]
None
[1 2 3]
[1 2 3 4 5]


In [41]:
print(np.insert(a,1,99))
print(a)

[ 1 99  2  3]
[1 2 3]


In [43]:
c=np.delete(a,0)
print(a)
print(c)

[1 2 3]
[2 3]


In [46]:
a=np.array([3,1,4,5,9,2])
print(a)
b=np.sort(a)
print(b)
np.unique(a)
print(a)

[3 1 4 5 9 2]
[1 2 3 4 5 9]
[3 1 4 5 9 2]


In [50]:
a=np.array([3,1,4,5,9,2])
print(a)
print(np.unique(a))
b=a[::-1]
print(b)

[3 1 4 5 9 2]
[1 2 3 4 5 9]
[2 9 5 4 1 3]
