In [ ]:
import numpy as np

students = np.array(["Harsh", "nigga", "Utkarsh", "Aditya", "dickshant"])

marks = np.array([
    [85, 90, 78, 92, 88],
    [70, 75, 80, 72, 68],
    [95, 98, 94, 97, 96],
    [60, 65, 58, 62, 64],
    [88, 84, 91, 87, 90]
])

print("Students:")
print(students)
print("\nMarks:")
print(marks)


print("\nRanking:")


print("\nClass Average =", class_avg)

print("\nStudents Above Class Average:")





print("\nPercentage:")
for i in range(len(students)):
    print(students[i], ":", percentage[i], "%")

labels = students
values = percentage

print("\nVisualization Ready Data")
print("Labels:", labels)
print("Values:", values)

Students:
['Harsh' 'Laukik' 'Utkarsh' 'Aditya' 'Dishant']

Marks:
[[85 90 78 92 88]
 [70 75 80 72 68]
 [95 98 94 97 96]
 [60 65 58 62 64]
 [88 84 91 87 90]]

Average Marks:
Harsh : 86.6
Laukik : 73.0
Utkarsh : 96.0
Aditya : 61.8
Dishant : 88.0

Highest and Lowest Marks:
Harsh Highest = 92 Lowest = 78
Laukik Highest = 80 Lowest = 68
Utkarsh Highest = 98 Lowest = 94
Aditya Highest = 65 Lowest = 58
Dishant Highest = 91 Lowest = 84

Standard Deviation:
Harsh : 4.88
Laukik : 4.2
Utkarsh : 1.41
Aditya : 2.56
Dishant : 2.45

Ranking:
Utkarsh : 96.0
Dishant : 88.0
Harsh : 86.6
Laukik : 73.0
Aditya : 61.8

Class Average = 81.08

Students Above Class Average:
Harsh
Utkarsh
Dishant

Subject-wise Average:
Subject 1 : 79.6
Subject 2 : 82.4
Subject 3 : 80.2
Subject 4 : 82.0
Subject 5 : 81.2

Percentage:
Harsh : 86.6 %
Laukik : 73.0 %
Utkarsh : 96.0 %
Aditya : 61.8 %
Dishant : 88.0 %

Visualization Ready Data
Labels: ['Harsh' 'Laukik' 'Utkarsh' 'Aditya' 'Dishant']
Values: [86.6 73.  96.  61.8 88. ]


In [ ]:
print("\nSubject-wise Average:")
for i in range(len(subject_avg)):
    print("Subject", i + 1, ":", subject_avg[i])


In [ ]:
for i in rank:
    print(students[i], ":", avg[i])
class_avg = np.mean(avg)

In [ ]:
for i in range(len(students)):
    if avg[i] > class_avg:
        print(students[i])
subject_avg = np.mean(marks, axis=0)


In [ ]:
for i in range(len(students)):
    print(students[i], ":", round(np.std(marks[i]), 2))
rank = np.argsort(avg)[::-1]

In [ ]:
print("\nHighest and Lowest Marks:")
for i in range(len(students)):
    print(students[i], "Highest =", np.max(marks[i]), "Lowest =", np.min(marks[i]))
print("\nStandard Deviation:")

In [ ]:
avg = np.mean(marks, axis=1)
print("\nAverage Marks:")
for i in range(len(students)):
    print(students[i], ":", avg[i])